services:
  web:
    image: falsesolutionn/my-node-app:latest
    container_name: my-node-app-production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
